# Here are gathered automatic (generic, pattern-based) rules for Mobile.
#
# See GNUmakerules-explicit.inc for the explicit (immediate, static)
# counterparts.


# Prerequisite: MOBILE_TOP must be set.


# Add all Mobile-specific rules below.


# Outside prerequisites: the modules from Ceylan-Seaplus, and libgammu.


# Allows any upper layer to override as a whole the Mobile rules used to compile
# classes and other modules:
#
ifndef OVERRIDE_MOBILE_BUILD_RULES


endif
