name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.2.0

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        echo "## Listing repositories"
        cat /etc/apt/sources.list
        echo "## Updating ubuntu (1/2)"
        apt-get update
        echo "## Installing add-apt-repository"
        apt-get install --assume-yes software-properties-common
        echo "## Adding universe"
        add-apt-repository universe
        echo "## Updating ubuntu (2/2)"
        apt-get update
        echo "## Installing Gammu"
        apt-get install --assume-yes libgammu
        rebar3 compile
    - name: Run tests
      run: make test NODE_NAMING="--sn"
