name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.2.0

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        apt-get update
        apt-get install --assume-yes software-properties-common
        add-apt-repository universe
        apt-get update
        apt-get install --assume-yes gammu
        rebar3 compile
    - name: Run tests
      run: make test NODE_NAMING="--sn"
